/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SalesIndexRouteImport } from './routes/sales/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CashIndexRouteImport } from './routes/cash/index'
import { Route as SalesDailyIndexRouteImport } from './routes/sales/daily.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashIndexRoute = CashIndexRouteImport.update({
  id: '/cash/',
  path: '/cash/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesDailyIndexRoute = SalesDailyIndexRouteImport.update({
  id: '/sales/daily/',
  path: '/sales/daily/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cash/': typeof CashIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sales/daily/': typeof SalesDailyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cash': typeof CashIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/products': typeof ProductsIndexRoute
  '/register': typeof RegisterIndexRoute
  '/sales': typeof SalesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sales/daily': typeof SalesDailyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cash/': typeof CashIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sales/daily/': typeof SalesDailyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cash/'
    | '/dashboard/'
    | '/login/'
    | '/products/'
    | '/register/'
    | '/sales/'
    | '/settings/'
    | '/sales/daily/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cash'
    | '/dashboard'
    | '/login'
    | '/products'
    | '/register'
    | '/sales'
    | '/settings'
    | '/sales/daily'
  id:
    | '__root__'
    | '/'
    | '/cash/'
    | '/dashboard/'
    | '/login/'
    | '/products/'
    | '/register/'
    | '/sales/'
    | '/settings/'
    | '/sales/daily/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashIndexRoute: typeof CashIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SalesDailyIndexRoute: typeof SalesDailyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash/': {
      id: '/cash/'
      path: '/cash'
      fullPath: '/cash/'
      preLoaderRoute: typeof CashIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/daily/': {
      id: '/sales/daily/'
      path: '/sales/daily'
      fullPath: '/sales/daily/'
      preLoaderRoute: typeof SalesDailyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashIndexRoute: CashIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SalesDailyIndexRoute: SalesDailyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
