/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as SalesReportIndexRouteImport } from './routes/sales/report.index'
import { Route as SalesListIndexRouteImport } from './routes/sales/list.index'
import { Route as SalesDailyIndexRouteImport } from './routes/sales/daily.index'
import { Route as ProductsReportIndexRouteImport } from './routes/products/report.index'
import { Route as ProductsListIndexRouteImport } from './routes/products/list.index'
import { Route as CashReportIndexRouteImport } from './routes/cash/report.index'
import { Route as CashListIndexRouteImport } from './routes/cash/list.index'
import { Route as CashCurrentIndexRouteImport } from './routes/cash/current.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesReportIndexRoute = SalesReportIndexRouteImport.update({
  id: '/sales/report/',
  path: '/sales/report/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesListIndexRoute = SalesListIndexRouteImport.update({
  id: '/sales/list/',
  path: '/sales/list/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesDailyIndexRoute = SalesDailyIndexRouteImport.update({
  id: '/sales/daily/',
  path: '/sales/daily/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsReportIndexRoute = ProductsReportIndexRouteImport.update({
  id: '/products/report/',
  path: '/products/report/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsListIndexRoute = ProductsListIndexRouteImport.update({
  id: '/products/list/',
  path: '/products/list/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashReportIndexRoute = CashReportIndexRouteImport.update({
  id: '/cash/report/',
  path: '/cash/report/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashListIndexRoute = CashListIndexRouteImport.update({
  id: '/cash/list/',
  path: '/cash/list/',
  getParentRoute: () => rootRouteImport,
} as any)
const CashCurrentIndexRoute = CashCurrentIndexRouteImport.update({
  id: '/cash/current/',
  path: '/cash/current/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/cash/current/': typeof CashCurrentIndexRoute
  '/cash/list/': typeof CashListIndexRoute
  '/cash/report/': typeof CashReportIndexRoute
  '/products/list/': typeof ProductsListIndexRoute
  '/products/report/': typeof ProductsReportIndexRoute
  '/sales/daily/': typeof SalesDailyIndexRoute
  '/sales/list/': typeof SalesListIndexRoute
  '/sales/report/': typeof SalesReportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/login': typeof LoginIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/register': typeof RegisterIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/cash/current': typeof CashCurrentIndexRoute
  '/cash/list': typeof CashListIndexRoute
  '/cash/report': typeof CashReportIndexRoute
  '/products/list': typeof ProductsListIndexRoute
  '/products/report': typeof ProductsReportIndexRoute
  '/sales/daily': typeof SalesDailyIndexRoute
  '/sales/list': typeof SalesListIndexRoute
  '/sales/report': typeof SalesReportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/login/': typeof LoginIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/cash/current/': typeof CashCurrentIndexRoute
  '/cash/list/': typeof CashListIndexRoute
  '/cash/report/': typeof CashReportIndexRoute
  '/products/list/': typeof ProductsListIndexRoute
  '/products/report/': typeof ProductsReportIndexRoute
  '/sales/daily/': typeof SalesDailyIndexRoute
  '/sales/list/': typeof SalesListIndexRoute
  '/sales/report/': typeof SalesReportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients/'
    | '/dashboard/'
    | '/login/'
    | '/onboarding/'
    | '/register/'
    | '/settings/'
    | '/cash/current/'
    | '/cash/list/'
    | '/cash/report/'
    | '/products/list/'
    | '/products/report/'
    | '/sales/daily/'
    | '/sales/list/'
    | '/sales/report/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/settings'
    | '/cash/current'
    | '/cash/list'
    | '/cash/report'
    | '/products/list'
    | '/products/report'
    | '/sales/daily'
    | '/sales/list'
    | '/sales/report'
  id:
    | '__root__'
    | '/'
    | '/clients/'
    | '/dashboard/'
    | '/login/'
    | '/onboarding/'
    | '/register/'
    | '/settings/'
    | '/cash/current/'
    | '/cash/list/'
    | '/cash/report/'
    | '/products/list/'
    | '/products/report/'
    | '/sales/daily/'
    | '/sales/list/'
    | '/sales/report/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  CashCurrentIndexRoute: typeof CashCurrentIndexRoute
  CashListIndexRoute: typeof CashListIndexRoute
  CashReportIndexRoute: typeof CashReportIndexRoute
  ProductsListIndexRoute: typeof ProductsListIndexRoute
  ProductsReportIndexRoute: typeof ProductsReportIndexRoute
  SalesDailyIndexRoute: typeof SalesDailyIndexRoute
  SalesListIndexRoute: typeof SalesListIndexRoute
  SalesReportIndexRoute: typeof SalesReportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/report/': {
      id: '/sales/report/'
      path: '/sales/report'
      fullPath: '/sales/report/'
      preLoaderRoute: typeof SalesReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/list/': {
      id: '/sales/list/'
      path: '/sales/list'
      fullPath: '/sales/list/'
      preLoaderRoute: typeof SalesListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/daily/': {
      id: '/sales/daily/'
      path: '/sales/daily'
      fullPath: '/sales/daily/'
      preLoaderRoute: typeof SalesDailyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/report/': {
      id: '/products/report/'
      path: '/products/report'
      fullPath: '/products/report/'
      preLoaderRoute: typeof ProductsReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/list/': {
      id: '/products/list/'
      path: '/products/list'
      fullPath: '/products/list/'
      preLoaderRoute: typeof ProductsListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash/report/': {
      id: '/cash/report/'
      path: '/cash/report'
      fullPath: '/cash/report/'
      preLoaderRoute: typeof CashReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash/list/': {
      id: '/cash/list/'
      path: '/cash/list'
      fullPath: '/cash/list/'
      preLoaderRoute: typeof CashListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash/current/': {
      id: '/cash/current/'
      path: '/cash/current'
      fullPath: '/cash/current/'
      preLoaderRoute: typeof CashCurrentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  CashCurrentIndexRoute: CashCurrentIndexRoute,
  CashListIndexRoute: CashListIndexRoute,
  CashReportIndexRoute: CashReportIndexRoute,
  ProductsListIndexRoute: ProductsListIndexRoute,
  ProductsReportIndexRoute: ProductsReportIndexRoute,
  SalesDailyIndexRoute: SalesDailyIndexRoute,
  SalesListIndexRoute: SalesListIndexRoute,
  SalesReportIndexRoute: SalesReportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
