import type { CurrentCash, CurrentSale, Product } from "@/lib/api-types"

export const dashboardFixtures = {
    cash: {
        status: "open",
        amounts: { expectedClosing: 1240.5 },
    },
    saleItems: 4,
    saleTotal: 186.9,
    todaySalesCount: 12,
    todaySalesTotal: 1240.5,
    productsCount: 38,
    lowStock: [
        { name: "Café Torrado 500g", stock: 0 },
        { name: "Coca-Cola Lata 350ml", stock: 0 },
        { name: "Detergente Neutro 500ml", stock: 0 },
    ],
    lastSales: [
        { client: "Maria Souza", total: 42.9 },
        { client: "cliente não informado", total: 18.5 },
        { client: "João Pereira", total: 93.0 },
    ],
} as const

export const pdvFixtures: NonNullable<CurrentSale> = {
    id: "a1b2c3d4-0000-4000-8000-000000000001",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    client: { id: 1, name: "Maria Souza" },
    payment: [{ amount: 186.9 }],
    saleItem: [
        {
            id: "a1b2c3d4-0000-4000-8000-000000000011",
            saleId: "a1b2c3d4-0000-4000-8000-000000000001",
            productId: 1,
            quantity: 2,
            totalPrice: 18.9,
            unitPrice: 9.45,
            createdAt: new Date().toISOString(),
            discount: 0,
            deletedAt: null,
            deleteReason: null,
            product: { id: 1, name: "Coca-Cola Lata 350ml" },
        },
        {
            id: "a1b2c3d4-0000-4000-8000-000000000012",
            saleId: "a1b2c3d4-0000-4000-8000-000000000001",
            productId: 2,
            quantity: 1,
            totalPrice: 42.9,
            unitPrice: 42.9,
            createdAt: new Date().toISOString(),
            discount: 0,
            deletedAt: null,
            deleteReason: null,
            product: { id: 2, name: "Café Torrado 500g" },
        },
        {
            id: "a1b2c3d4-0000-4000-8000-000000000013",
            saleId: "a1b2c3d4-0000-4000-8000-000000000001",
            productId: 3,
            quantity: 1,
            totalPrice: 125.1,
            unitPrice: 139.0,
            createdAt: new Date().toISOString(),
            discount: 13.9,
            deletedAt: null,
            deleteReason: null,
            product: { id: 3, name: "Arroz Integral 5kg" },
        },
        {
            id: "a1b2c3d4-0000-4000-8000-000000000014",
            saleId: "a1b2c3d4-0000-4000-8000-000000000001",
            productId: 4,
            quantity: 1,
            totalPrice: 0,
            unitPrice: 0,
            createdAt: new Date().toISOString(),
            discount: 0,
            deletedAt: new Date().toISOString(),
            deleteReason: "item cancelado",
            product: { id: 4, name: "Sabão em Pó 1kg" },
        },
    ],
}

export const catalogFixtures: Product[] = [
    {
        id: 1,
        name: "Coca-Cola Lata 350ml",
        sellPrice: 9.45,
        buyPrice: 5.8,
        gtin: "7894900011517",
        category: { id: 1, name: "Bebidas" },
        stockMovement: [
            { quantity: 40, type: "in" },
            { quantity: 12, type: "out" },
            { quantity: 6, type: "out" },
        ],
    },
    {
        id: 2,
        name: "Café Torrado 500g",
        sellPrice: 42.9,
        buyPrice: 31.2,
        gtin: "7892840219141",
        category: { id: 2, name: "Mercearia" },
        stockMovement: [
            { quantity: 24, type: "in" },
            { quantity: 9, type: "out" },
            { quantity: 15, type: "out" },
        ],
    },
    {
        id: 3,
        name: "Arroz Integral 5kg",
        sellPrice: 139.0,
        buyPrice: 102.5,
        gtin: "7898919238102",
        category: { id: 2, name: "Mercearia" },
        stockMovement: [
            { quantity: 18, type: "in" },
            { quantity: 4, type: "out" },
        ],
    },
    {
        id: 4,
        name: "Sabão em Pó 1kg",
        sellPrice: 18.7,
        buyPrice: 12.4,
        gtin: "7891150056391",
        category: { id: 3, name: "Limpeza" },
        stockMovement: [
            { quantity: 30, type: "in" },
            { quantity: 30, type: "out" },
        ],
    },
    {
        id: 5,
        name: "Detergente Neutro 500ml",
        sellPrice: 6.2,
        buyPrice: 3.1,
        gtin: "7896094908202",
        category: { id: 3, name: "Limpeza" },
        stockMovement: [
            { quantity: 28, type: "in" },
            { quantity: 14, type: "out" },
            { quantity: 14, type: "out" },
        ],
    },
    {
        id: 6,
        name: "Pão Francês (kg)",
        sellPrice: 24.9,
        buyPrice: 15.0,
        gtin: null,
        category: { id: 4, name: "Padaria" },
        stockMovement: [
            { quantity: 10, type: "in" },
            { quantity: 3, type: "out" },
            { quantity: 5, type: "out" },
        ],
    },
]

export const cashFixtures: NonNullable<CurrentCash> = {
    id: "b2c3d4e5-0000-4000-8000-000000000001",
    status: "open",
    openedAt: new Date().toISOString(),
    closedAt: null,
    amounts: {
        opening: 200,
        inflow: 1240.5,
        outflow: 385.2,
        expectedClosing: 1055.3,
        actualClosing: null,
        difference: null,
    },
    users: {
        createdBy: { id: "user-1", login: "admin" },
        updatedBy: null,
        closedBy: null,
    },
    paymentSummary: [
        { method: "cash", amount: 512.4, salesCount: 5 },
        { method: "pix", amount: 418.6, salesCount: 4 },
        { method: "debit", amount: 166.0, salesCount: 2 },
        { method: "credit", amount: 89.5, salesCount: 1 },
        { method: "voucher", amount: 0, salesCount: 0 },
    ],
    movementSummary: {
        totalCount: 5,
        inCount: 3,
        outCount: 2,
    },
    movements: [
        {
            id: "m1",
            type: "payment",
            nature: "in",
            amount: 1240.5,
            signedAmount: 1240.5,
            description: "vendas do dia",
            reference: { type: "payment", id: "p1" },
            createdAt: new Date().toISOString(),
            createdByUser: { id: "user-1", login: "admin" },
        },
        {
            id: "m2",
            type: "drop",
            nature: "out",
            amount: 85.2,
            signedAmount: -85.2,
            description: "compra de sacolas e embalagens",
            reference: null,
            createdAt: new Date().toISOString(),
            createdByUser: { id: "user-1", login: "admin" },
        },
        {
            id: "m3",
            type: "topup",
            nature: "in",
            amount: 300.0,
            signedAmount: 300.0,
            description: "sangria do caixa",
            reference: { type: "manual", id: "c1" },
            createdAt: new Date().toISOString(),
            createdByUser: { id: "user-1", login: "admin" },
        },
        {
            id: "m4",
            type: "drop",
            nature: "out",
            amount: 300.0,
            signedAmount: -300.0,
            description: "sangria",
            reference: null,
            createdAt: new Date().toISOString(),
            createdByUser: { id: "user-1", login: "admin" },
        },
        {
            id: "m5",
            type: "open",
            nature: "in",
            amount: 0,
            signedAmount: 0,
            description: "abertura de caixa",
            reference: { type: "payment", id: "p0" },
            createdAt: new Date().toISOString(),
            createdByUser: null,
        },
    ],
}